name: Cron

on:
  schedule:
    - cron: "5 10 9 * *"

jobs:
  ci:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: --health-cmd='pg_isready' --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['master']
        php: ['7.4']
        database: ['pgsql']

    name: ${{ matrix.moodle-branch }}  php ${{ matrix.php }}  ${{ matrix.database }}

    steps:
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          path: this-plugin

      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, mysqli, gd, zip

      - name: checkout moodle-plugin-ci
        uses: actions/checkout@v2
        with:
          repository: moodlehq/moodle-plugin-ci
          path: ci

      - name: composer
        run: |
           composer install
           echo "$(cd bin; pwd)" >> $GITHUB_PATH
           echo "$(cd vendor/bin; pwd)" >> $GITHUB_PATH
           sudo locale-gen en_AU.UTF-8
        working-directory: ci

      - name: add plugin
        run: moodle-plugin-ci add-plugin --clone https://github.com/ewallah/moodle-local_aws.git --branch main

      - name: install Moodle
        run: moodle-plugin-ci install --db-host=127.0.0.1 --plugin this-plugin
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: phplint
        run: moodle-plugin-ci phplint --ansi

      - name: phpcpd
        run: moodle-plugin-ci phpcpd --ansi

      - name: phpmd
        run: moodle-plugin-ci phpmd --ansi

      - name: codechecker
        run: moodle-plugin-ci codechecker --ansi

      - name: validate
        run: moodle-plugin-ci validate --ansi

      - name: savepoints
        run: moodle-plugin-ci savepoints --ansi

      - name: mustache
        run: moodle-plugin-ci mustache --ansi

      - name: grunt
        run: moodle-plugin-ci grunt --ansi

      - name: phpunit 
        run: moodle-plugin-ci phpunit --ansi --coverage-text

      - name: firefox
        run: moodle-plugin-ci behat --ansi
